<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/andrei/buildkit/build/aws/web/wp-content/uploads/civicrm/ext/aws/xml/schema/CRM/Aws/MailingConfigSet.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d1c6b49aa2d8240721b95344528c2dff)
 */

/**
 * Database access object for the MailingConfigSet entity.
 */
class CRM_Aws_DAO_MailingConfigSet extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mailing_config_set';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MailingConfigSet ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Mailing
   *
   * @var int
   */
  public $mailing_id;

  /**
   * The SES configuration set name for open/click tracking.
   *
   * @var text
   */
  public $config_set;

  /**
   * Is SES tracking enabled for this mailing?
   *
   * @var bool
   */
  public $is_active;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailing_config_set';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mailing_id', 'civicrm_mailing', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Aws_ExtensionUtil::ts('Unique MailingConfigSet ID'),
          'where' => 'civicrm_mailing_config_set.id',
          'table_name' => 'civicrm_mailing_config_set',
          'entity' => 'MailingConfigSet',
          'bao' => 'CRM_Aws_DAO_MailingConfigSet',
          'localizable' => 0,
        ],
        'mailing_id' => [
          'name' => 'mailing_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Aws_ExtensionUtil::ts('Mailing Id'),
          'description' => CRM_Aws_ExtensionUtil::ts('FK to Mailing'),
          'required' => TRUE,
          'where' => 'civicrm_mailing_config_set.mailing_id',
          'table_name' => 'civicrm_mailing_config_set',
          'entity' => 'MailingConfigSet',
          'bao' => 'CRM_Aws_DAO_MailingConfigSet',
          'localizable' => 0,
        ],
        'config_set' => [
          'name' => 'config_set',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Aws_ExtensionUtil::ts('Config Set'),
          'description' => CRM_Aws_ExtensionUtil::ts('The SES configuration set name for open/click tracking.'),
          'where' => 'civicrm_mailing_config_set.config_set',
          'table_name' => 'civicrm_mailing_config_set',
          'entity' => 'MailingConfigSet',
          'bao' => 'CRM_Aws_DAO_MailingConfigSet',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Aws_Ses_BAO_Ses::getConfigurationSets',
          ],
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Aws_ExtensionUtil::ts('SES tracking enabled?'),
          'description' => CRM_Aws_ExtensionUtil::ts('Is SES tracking enabled for this mailing?'),
          'where' => 'civicrm_mailing_config_set.is_active',
          'default' => '0',
          'table_name' => 'civicrm_mailing_config_set',
          'entity' => 'MailingConfigSet',
          'bao' => 'CRM_Aws_DAO_MailingConfigSet',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailing_config_set', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailing_config_set', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
