<?php
/**
 * AWS settings.
 *
 * @since 1.0
 */
return [
  'aws_access_key' => [
    'name' => 'aws_access_key',
    'type' => CRM_Utils_Type::T_STRING,
    'settings_pages' => ['aws-credentials' => ['weight' => 10]],
    'html_type' => 'text',
    'default' => '',
    'title' => ts('AWS access key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The IAM user access key.'),
    'help_text' => ts('The IAM user access key.'),
  ],
  'aws_secret_key' => [
    'name' => 'aws_secret_key',
    'type' => CRM_Utils_Type::T_STRING,
    'settings_pages' => ['aws-credentials' => ['weight' => 20]],
    'html_type' => 'text',
    'default' => '',
    'title' => ts('AWS secret key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The IAM user secret key'),
    'help_text' => ts('The IAM user secret key'),
  ],
  'aws_region' => [
    'name' => 'aws_region',
    'type' => CRM_Utils_Type::T_STRING,
    'settings_pages' => ['aws-credentials' => ['weight' => 30]],
    'html_type' => 'select',
    'html_attributes' => [ 'class' => 'crm-select2' ],
    'default' => 'eu-west-1',
    'pseudoconstant' => [ 'callback' => 'CRM_Aws_Utils::getRegions', ],
    'title' => ts('AWS Region'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The AWS region.'),
    'help_text' => ts('The AWS region.'),
  ],
  'aws_ses_use_api' => [
    'name' => 'aws_ses_use_api',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'settings_pages' => ['aws-ses' => ['weight' => 10]],
    'html_type' => 'radio',
    'default' => 0,
    'title' => ts('Use AWS SES API?'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Use SES API to send emails instead of SMTP (NOT YET FUNCTIONAL).'),
    'help_text' => ts('Use SES API to send emails instead of SMTP.'),
  ],
  'aws_ses_default_config_set' => [
    'name' => 'aws_ses_default_config_set',
    'type' => CRM_Utils_Type::T_STRING,
    'settings_pages' => ['aws-ses' => ['weight' => 20]],
    'html_type' => 'select',
    'html_attributes' => ['class' => 'crm-select2'],
    'default' => 'eu-west-1',
    'pseudoconstant' => ['callback' => 'CRM_Aws_Ses_BAO_Ses::getConfigurationSets',],
    'title' => ts('Default Configuration Set'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The default SES Configuration Set for open/click tracking.'),
    'help_text' => ts('The default SES Configuration Set for open/click tracking.'),
  ],
];
